/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fleurducoeur;

import pages.PageFleurs;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Lioz-MBPR
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    
    public Accueil() {
        initComponents();
        
        ChangeListener changeListener = new ChangeListener() {
          public void stateChanged(ChangeEvent changeEvent) {
            JTabbedPane sourceTabbedPane = (JTabbedPane) changeEvent.getSource();
            int index = sourceTabbedPane.getSelectedIndex();
            if (sourceTabbedPane.getTitleAt(index) == "Fleurs"){
                Container container1 = pageFleurs2;
                container1.removeAll();
                container1.add(new PageFleurs());
            }
          }
        };
        tabs.addChangeListener(changeListener);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        enTetePanel = new javax.swing.JPanel();
        buttunAccueil = new javax.swing.JButton();
        tabs = new javax.swing.JTabbedPane();
        pageAccueil1 = new pages.PageAccueil();
        pageFleurs2 = new pages.PageFleurs();
        bouquets1 = new pages.PageBouquets();
        occasions1 = new pages.PageOccasions();
        patience1 = new pages.PagePatience();
        recupererSesFleurs1 = new pages.PageRecupererSesFleurs();
        pagePanier2 = new pages.PagePanier();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FleurDuCoeur");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        container.setLayout(new java.awt.BorderLayout());

        enTetePanel.setMinimumSize(new java.awt.Dimension(100, 60));
        enTetePanel.setPreferredSize(new java.awt.Dimension(388, 60));

        buttunAccueil.setBackground(new java.awt.Color(255, 255, 255));
        buttunAccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fleurducoeur/logo.png"))); // NOI18N
        buttunAccueil.setText("FleurDuCoeur");
        buttunAccueil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttunAccueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttunAccueilMousePressed(evt);
            }
        });

        javax.swing.GroupLayout enTetePanelLayout = new javax.swing.GroupLayout(enTetePanel);
        enTetePanel.setLayout(enTetePanelLayout);
        enTetePanelLayout.setHorizontalGroup(
            enTetePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enTetePanelLayout.createSequentialGroup()
                .addComponent(buttunAccueil, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addContainerGap())
        );
        enTetePanelLayout.setVerticalGroup(
            enTetePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enTetePanelLayout.createSequentialGroup()
                .addComponent(buttunAccueil)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        container.add(enTetePanel, java.awt.BorderLayout.PAGE_START);

        tabs.setForeground(new java.awt.Color(102, 102, 102));

        pageAccueil1.setPreferredSize(new java.awt.Dimension(500, 386));
        tabs.addTab("Accueil", pageAccueil1);
        tabs.addTab("Fleurs", pageFleurs2);

        javax.swing.GroupLayout bouquets1Layout = new javax.swing.GroupLayout(bouquets1);
        bouquets1.setLayout(bouquets1Layout);
        bouquets1Layout.setHorizontalGroup(
            bouquets1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        bouquets1Layout.setVerticalGroup(
            bouquets1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tabs.addTab("Catégorie de bouquets", bouquets1);

        javax.swing.GroupLayout occasions1Layout = new javax.swing.GroupLayout(occasions1);
        occasions1.setLayout(occasions1Layout);
        occasions1Layout.setHorizontalGroup(
            occasions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        occasions1Layout.setVerticalGroup(
            occasions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tabs.addTab("Occasions", occasions1);
        tabs.addTab("Patience", patience1);

        javax.swing.GroupLayout recupererSesFleurs1Layout = new javax.swing.GroupLayout(recupererSesFleurs1);
        recupererSesFleurs1.setLayout(recupererSesFleurs1Layout);
        recupererSesFleurs1Layout.setHorizontalGroup(
            recupererSesFleurs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        recupererSesFleurs1Layout.setVerticalGroup(
            recupererSesFleurs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tabs.addTab("Où récupérer ses fleurs ?", recupererSesFleurs1);
        tabs.addTab("Panier", pagePanier2);

        container.add(tabs, java.awt.BorderLayout.CENTER);
        tabs.getAccessibleContext().setAccessibleName("Accueil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttunAccueilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttunAccueilMousePressed
        /*BorderLayout layout = (BorderLayout)container.getLayout();
        Container container1 = this.getContentPane();
        container1.removeAll();
        container1.setLayout(layout);
        container1.add(enTetePanel);
        container1.add(new PageAccueil());
        container1.repaint();
        this.setVisible(true);*/
        tabs.setSelectedIndex(0);
        System.out.println("test");
    }//GEN-LAST:event_buttunAccueilMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pages.PageBouquets bouquets1;
    private javax.swing.JButton buttunAccueil;
    private javax.swing.JPanel container;
    private javax.swing.JPanel enTetePanel;
    private pages.PageOccasions occasions1;
    private pages.PageAccueil pageAccueil1;
    private pages.PageFleurs pageFleurs2;
    private pages.PagePanier pagePanier2;
    private pages.PagePatience patience1;
    private pages.PageRecupererSesFleurs recupererSesFleurs1;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
