/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fleurducoeur;

/**
 *
 * @author valentin
 */
public class ArticlePanel extends javax.swing.JPanel {
    
    private Article article;

    /**
     * Creates new form ArticlePanel
     */
    public ArticlePanel(Article art) {
        initComponents();
        this.article = art;
        picture = new ImagePanel(article.getAdresseImage());
        price.setText(toString(article.getPrix()));
    }
    
    public String toString(double prix){
        return ("Prix : "+ prix+ " €");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picture = new javax.swing.JPanel();
        price = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(2147483647, 300));
        setLayout(new java.awt.BorderLayout());

        picture.setPreferredSize(new java.awt.Dimension(300, 300));
        add(picture, java.awt.BorderLayout.PAGE_START);

        price.setText("jLabel1");
        add(price, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel picture;
    private javax.swing.JLabel price;
    // End of variables declaration//GEN-END:variables
}
