/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pages;


import fleurducoeur.ArticlePanel;
import objets.Fleur;
import statesmachines.StateMachineCouleur;
import statesmachines.StateMachineTaille;
import statesmachines.StateMachinePrix;
import java.awt.GridLayout;
import java.util.ArrayList;

/**
 *
 * @author Lioz-MBPR
 */
public class PageFleurs extends javax.swing.JPanel {


    private StateMachineCouleur stateMachineCouleur;
    private StateMachineTaille stateMachineTaille;
    private StateMachinePrix stateMachinePrix;
    
    private ArrayList<ArticlePanel> listeArticles;
    
    public ArrayList<ArticlePanel> getListeArticles (){
        return listeArticles;
    }
    public void setListeArticles (ArrayList liste)
    {
        listeArticles = liste;
    }
    
    /**
     * Creates new form PageFleurs
     */
    public PageFleurs() {
        initComponents();
        
        
        listeArticles = new ArrayList<>();
        
        listeArticles.add(new ArticlePanel(new Fleur("Amour", 15.60, "Rose", "Rouge", "./images/Rouge.png",4, "Moyen")));
        listeArticles.add(new ArticlePanel(new Fleur("Amour", 36, "Rose", "Rose", "./images/Rose.png",4, "Moyen")));
        listeArticles.add(new ArticlePanel(new Fleur("Cocu", 55, "Tulipe", "Jaune", "./images/Jaune.png",4, "Grand")));
        listeArticles.add(new ArticlePanel(new Fleur("Senteur", 21, "Lavandes", "Violet", "./images/Lavandes.png",4, "Moyen")));
        listeArticles.add(new ArticlePanel(new Fleur("Dur", 45, "Orchidées", "Varie", "./images/Orchidées.png",4, "Petit")));
        listeArticles.add(new ArticlePanel(new Fleur("1Mai", 1, "Muguet", "Blanche", "./images/Muguet.png",4, "Petit")));
        listeArticles.add(new ArticlePanel(new Fleur("Champs", 34.45, "Maguerite", "Blanche", "./images/Marguerites.png",4, "Grand")));
        //listeArticles.add(new ArticlePanel(new Fleur("Amour", 15.60, "Rose", "Rouge", "./images/fleur.jpg",4, "Petit")));
        //listeArticles.add(new ArticlePanel(new Fleur("Amour", 15.60, "Rose", "Rouge", "./images/fleur.jpg",4, "Petit")));
        
        
        
        stateMachineCouleur = new StateMachineCouleur(this);
        stateMachinePrix = new StateMachinePrix(this);
        stateMachineTaille = new StateMachineTaille(this);
        
        for (ArticlePanel art : listeArticles) {
            fleurs.add(art);
        }
        
    }
    
    private void refresh () {
        fleurs.removeAll();
        for (ArticlePanel article : listeArticles) {
            System.out.println(article.isVisibleColor() + " " + article.isVisibleTaille() + "    " + article.isVisiblePrix());
            if (article.isVisibleColor() && article.isVisibleTaille() && article.isVisiblePrix())
                fleurs.add(article);
        }
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorGroup = new javax.swing.ButtonGroup();
        priceGroup = new javax.swing.ButtonGroup();
        varietyGroup = new javax.swing.ButtonGroup();
        filter = new javax.swing.JPanel();
        whiteBtn = new javax.swing.JRadioButton();
        redBtn = new javax.swing.JRadioButton();
        pinkBtn = new javax.swing.JRadioButton();
        yellowBtn = new javax.swing.JRadioButton();
        purpleBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lowBtn = new javax.swing.JRadioButton();
        middleLowBtn = new javax.swing.JRadioButton();
        middleHighBtn = new javax.swing.JRadioButton();
        highBtn = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        littleBtn = new javax.swing.JRadioButton();
        middleBtn = new javax.swing.JRadioButton();
        bigBtn = new javax.swing.JRadioButton();
        varieBtn = new javax.swing.JRadioButton();
        fleurs = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        filter.setBackground(new java.awt.Color(254, 254, 254));
        filter.setPreferredSize(new java.awt.Dimension(175, 382));

        colorGroup.add(whiteBtn);
        whiteBtn.setText("Blanc");
        whiteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                whiteBtnMouseClicked(evt);
            }
        });

        colorGroup.add(redBtn);
        redBtn.setText("Rouge");
        redBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redBtnMouseClicked(evt);
            }
        });

        colorGroup.add(pinkBtn);
        pinkBtn.setText("Rose");
        pinkBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pinkBtnMouseClicked(evt);
            }
        });

        colorGroup.add(yellowBtn);
        yellowBtn.setText("Jaune");
        yellowBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yellowBtnMouseClicked(evt);
            }
        });

        colorGroup.add(purpleBtn);
        purpleBtn.setText("Violet");
        purpleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purpleBtnMouseClicked(evt);
            }
        });

        jLabel1.setText("Couleur");

        jLabel2.setText("Prix");

        priceGroup.add(lowBtn);
        lowBtn.setText("<30€");
        lowBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lowBtnMouseClicked(evt);
            }
        });

        priceGroup.add(middleLowBtn);
        middleLowBtn.setText("30-40€");
        middleLowBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                middleLowBtnMouseClicked(evt);
            }
        });

        priceGroup.add(middleHighBtn);
        middleHighBtn.setText("40-50€");
        middleHighBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                middleHighBtnMouseClicked(evt);
            }
        });

        priceGroup.add(highBtn);
        highBtn.setText(">50€");
        highBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                highBtnMouseClicked(evt);
            }
        });

        jLabel3.setText("Taille");

        varietyGroup.add(littleBtn);
        littleBtn.setText("Petit");
        littleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                littleBtnMouseClicked(evt);
            }
        });

        varietyGroup.add(middleBtn);
        middleBtn.setText("Moyen");
        middleBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                middleBtnMouseClicked(evt);
            }
        });

        varietyGroup.add(bigBtn);
        bigBtn.setText("Grand");
        bigBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bigBtnMouseClicked(evt);
            }
        });

        colorGroup.add(varieBtn);
        varieBtn.setText("Varié");
        varieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varieBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filterLayout = new javax.swing.GroupLayout(filter);
        filter.setLayout(filterLayout);
        filterLayout.setHorizontalGroup(
            filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filterLayout.createSequentialGroup()
                        .addComponent(lowBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(middleLowBtn))
                    .addComponent(jLabel1)
                    .addGroup(filterLayout.createSequentialGroup()
                        .addComponent(whiteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purpleBtn))
                    .addGroup(filterLayout.createSequentialGroup()
                        .addComponent(redBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varieBtn))
                    .addComponent(jLabel2)
                    .addGroup(filterLayout.createSequentialGroup()
                        .addComponent(pinkBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yellowBtn))
                    .addComponent(jLabel3)
                    .addComponent(littleBtn)
                    .addGroup(filterLayout.createSequentialGroup()
                        .addComponent(middleHighBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(highBtn))
                    .addComponent(bigBtn)
                    .addComponent(middleBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        filterLayout.setVerticalGroup(
            filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filterLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whiteBtn)
                    .addComponent(purpleBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinkBtn)
                    .addComponent(yellowBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redBtn)
                    .addComponent(varieBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lowBtn)
                    .addComponent(middleLowBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleHighBtn)
                    .addComponent(highBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(littleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(middleBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bigBtn)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        add(filter, java.awt.BorderLayout.LINE_START);

        fleurs.setLayout(new java.awt.GridLayout(3, 3));
        add(fleurs, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void whiteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_whiteBtnMouseClicked
        stateMachineCouleur.onMouseClickBlanche();
        this.refresh();
    }//GEN-LAST:event_whiteBtnMouseClicked

    private void purpleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purpleBtnMouseClicked
        stateMachineCouleur.onMouseClickViolet();
        this.refresh();
    }//GEN-LAST:event_purpleBtnMouseClicked

    private void pinkBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinkBtnMouseClicked
        stateMachineCouleur.onMouseClickRose();
        this.refresh();
    }//GEN-LAST:event_pinkBtnMouseClicked

    private void yellowBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowBtnMouseClicked
        stateMachineCouleur.onMouseClickJaune();
        this.refresh();
    }//GEN-LAST:event_yellowBtnMouseClicked

    private void redBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redBtnMouseClicked
        stateMachineCouleur.onMouseClickRouge();
        this.refresh();
    }//GEN-LAST:event_redBtnMouseClicked

    private void lowBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lowBtnMouseClicked
        stateMachinePrix.onMouseClickMoins30();
        this.refresh();
    }//GEN-LAST:event_lowBtnMouseClicked

    private void middleLowBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_middleLowBtnMouseClicked
        stateMachinePrix.onMouseClick30_40();
        this.refresh();
    }//GEN-LAST:event_middleLowBtnMouseClicked

    private void middleHighBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_middleHighBtnMouseClicked
        stateMachinePrix.onMouseClick40_50();
        this.refresh();
    }//GEN-LAST:event_middleHighBtnMouseClicked

    private void highBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highBtnMouseClicked
        stateMachinePrix.onMouseClickPlus50();
        this.refresh();
}//GEN-LAST:event_highBtnMouseClicked

    private void littleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_littleBtnMouseClicked
        stateMachineTaille.onMouseClickPetit();
        this.refresh();
    }//GEN-LAST:event_littleBtnMouseClicked

    private void middleBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_middleBtnMouseClicked
        stateMachineTaille.onMouseClickMoyen();
        this.refresh();
    }//GEN-LAST:event_middleBtnMouseClicked

    private void bigBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bigBtnMouseClicked
        stateMachineTaille.onMouseClickGrand();
        this.refresh();
    }//GEN-LAST:event_bigBtnMouseClicked

    private void varieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varieBtnActionPerformed
        stateMachineCouleur.onMouseClickVarie();
        this.refresh();
    }//GEN-LAST:event_varieBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bigBtn;
    private javax.swing.ButtonGroup colorGroup;
    private javax.swing.JPanel filter;
    private javax.swing.JPanel fleurs;
    private javax.swing.JRadioButton highBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton littleBtn;
    private javax.swing.JRadioButton lowBtn;
    private javax.swing.JRadioButton middleBtn;
    private javax.swing.JRadioButton middleHighBtn;
    private javax.swing.JRadioButton middleLowBtn;
    private javax.swing.JRadioButton pinkBtn;
    private javax.swing.ButtonGroup priceGroup;
    private javax.swing.JRadioButton purpleBtn;
    private javax.swing.JRadioButton redBtn;
    private javax.swing.JRadioButton varieBtn;
    private javax.swing.ButtonGroup varietyGroup;
    private javax.swing.JRadioButton whiteBtn;
    private javax.swing.JRadioButton yellowBtn;
    // End of variables declaration//GEN-END:variables
}
